version: "3"
services:
  typo3:
    image: dockerimages/typo3-9.5:php7.2-apache
    build: .
    ports:
      - "80"
    volumes:
      - fileadmin:/var/www/html/fileadmin
      - typo3conf:/var/www/html/typo3conf
      - uploads:/var/www/html/uploads
    networks:
      - backend
  database:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-typo3}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-typo3}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    networks:
      - backend
volumes:
  database:
  fileadmin:
  typo3conf:
  uploads:
networks:
  backend:
