version: "3"
services:
  php7.2:
    image: ${ORG:-dockerimages}/typo3-baseimage:php7.2-apache
    build: 
      context: ./baseimage
      args:
        - PHP_VERSION=7.2
  php5.6:
    image: ${ORG:-dockerimages}/typo3-baseimage:php5.6-apache
    build: 
      context: ./baseimage
      args:
        - PHP_VERSION=5.6
  typo3-9.5-php7.2:
    image: ${ORG:-dockerimages}/typo3:9.5-php7.2-apache
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "9.5"
  typo3-9.5:
    image: ${ORG:-dockerimages}/typo3:9.5
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "9.5"
  typo3-latest:
    image: ${ORG:-dockerimages}/typo3:latest
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "9.5"
  typo3-9.4:
    image: ${ORG:-dockerimages}/typo3:9.4-php7.2-apache
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "9.4"
  typo3-8.7-php7.2:
    image: ${ORG:-dockerimages}/typo3:8.7-php7.2-apache
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "8.7"
  typo3-8.7:
    image: ${ORG:-dockerimages}/typo3:8.7
    build: 
      context: .
      args:
        PHP_VERSION: "7.2"
        TYPO3_VERSION: "8.7"
  typo3-6.2:
    image: ${ORG:-dockerimages}/typo3:6.2-php5.6-apache
    build: 
      context: .
      args:
        PHP_VERSION: "5.6"
        TYPO3_VERSION: "6.2"
  typo3-7.6:
    image: ${ORG:-dockerimages}/typo3:7.6-php5.6-apache
    build: 
      context: .
      args:
        PHP_VERSION: "5.6"
        TYPO3_VERSION: "7.6"